### ISSUE TITLE
"cover-image" manifest item match, "properties" attribute contains space-separated tokens

### ISSUE THREAD

**Issue by danielweck** [thephilgray/get-epub-cover#2]
Strictly-speaking, the `opf/manifest/item@properties` attribute contains space-separated values, so the `===` string match can fail ... in principle (to be fair, in practice I have never come across other terms alongside `cover-image` ;)

https://github.com/thephilgray/get-epub-cover/blob/ebfce3a151ed47332b42c06a7607940fa0aca97e/index.js#L85-L87

Spec.:
http://www.idpf.org/epub/301/spec/epub-publications.html#sec-item-elem

**Comment by thephilgray** [comment]
fixed in v.1.0.5

Thanks!
